import { Share, Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { Transaction } from '../models/types';
import { formatCurrency } from '../utils/helpers';

function formatExportDate(timestamp: number): string {
  const d = new Date(timestamp);
  return d.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Generate CSV content from transactions
 */
export function generateCSV(transactions: Transaction[]): string {
  const headers = ['Date', 'Description', 'Merchant', 'Amount (INR)', 'Category', 'Source', 'Tracker', 'Tags', 'Note'];
  const rows = transactions
    .sort((a, b) => b.timestamp - a.timestamp)
    .map(t => [
      formatExportDate(t.timestamp),
      `"${(t.description || '').replace(/"/g, '""')}"`,
      `"${(t.merchant || '').replace(/"/g, '""')}"`,
      t.amount.toFixed(2),
      `"${t.category || ''}"`,
      `"${t.source || ''}"`,
      t.trackerType,
      `"${(t.tags || []).join(', ')}"`,
      `"${(t.note || '').replace(/"/g, '""')}"`,
    ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

/**
 * Generate a text summary report from transactions
 */
export function generateTextReport(transactions: Transaction[], periodLabel: string): string {
  const total = transactions.reduce((s, t) => s + t.amount, 0);
  const sorted = [...transactions].sort((a, b) => b.timestamp - a.timestamp);

  // Category breakdown
  const cats: Record<string, { amount: number; count: number }> = {};
  for (const t of transactions) {
    const cat = t.category || 'Other';
    if (!cats[cat]) cats[cat] = { amount: 0, count: 0 };
    cats[cat].amount += t.amount;
    cats[cat].count++;
  }

  const catLines = Object.entries(cats)
    .sort((a, b) => b[1].amount - a[1].amount)
    .map(([name, data]) => `  ${name}: ${formatCurrency(data.amount)} (${data.count} transactions)`)
    .join('\n');

  // Top merchants
  const merchants: Record<string, { amount: number; count: number }> = {};
  for (const t of transactions) {
    const m = t.merchant || t.description;
    if (!merchants[m]) merchants[m] = { amount: 0, count: 0 };
    merchants[m].amount += t.amount;
    merchants[m].count++;
  }

  const merchantLines = Object.entries(merchants)
    .sort((a, b) => b[1].amount - a[1].amount)
    .slice(0, 10)
    .map(([name, data], i) => `  ${i + 1}. ${name}: ${formatCurrency(data.amount)} (${data.count}x)`)
    .join('\n');

  return `TRACKK EXPENSE REPORT
${periodLabel}
${'='.repeat(40)}

SUMMARY
  Total Spent: ${formatCurrency(total)}
  Transactions: ${transactions.length}
  Avg per transaction: ${formatCurrency(transactions.length > 0 ? total / transactions.length : 0)}

CATEGORY BREAKDOWN
${catLines || '  No data'}

TOP MERCHANTS
${merchantLines || '  No data'}

TRANSACTIONS
${'─'.repeat(40)}
${sorted.map(t =>
    `  ${formatExportDate(t.timestamp)}  ${formatCurrency(t.amount).padStart(12)}  ${t.description}`
  ).join('\n')}

${'─'.repeat(40)}
Generated by Trackk on ${new Date().toLocaleDateString('en-IN')}`;
}

/**
 * Share CSV data as text
 */
export async function shareCSV(transactions: Transaction[]): Promise<void> {
  const csv = generateCSV(transactions);
  await Share.share({ message: csv, title: 'Trackk Expenses.csv' });
}

/**
 * Share text report
 */
export async function shareTextReport(transactions: Transaction[], periodLabel: string): Promise<void> {
  const report = generateTextReport(transactions, periodLabel);
  await Share.share({ message: report, title: `Trackk Report - ${periodLabel}` });
}

/**
 * Generate HTML for PDF export
 */
function generatePDFHTML(transactions: Transaction[], periodLabel: string): string {
  const total = transactions.reduce((s, t) => s + t.amount, 0);
  const sorted = [...transactions].sort((a, b) => b.timestamp - a.timestamp);

  // Category breakdown
  const cats: Record<string, { amount: number; count: number }> = {};
  for (const t of transactions) {
    const cat = t.category || 'Other';
    if (!cats[cat]) cats[cat] = { amount: 0, count: 0 };
    cats[cat].amount += t.amount;
    cats[cat].count++;
  }
  const catRows = Object.entries(cats)
    .sort((a, b) => b[1].amount - a[1].amount)
    .map(([name, data]) => `<tr><td>${name}</td><td style="text-align:right">${formatCurrency(data.amount)}</td><td style="text-align:center">${data.count}</td><td style="text-align:right">${total > 0 ? ((data.amount / total) * 100).toFixed(1) : 0}%</td></tr>`)
    .join('');

  const txnRows = sorted.map(t =>
    `<tr><td>${formatExportDate(t.timestamp)}</td><td>${t.merchant || t.description}</td><td>${t.category || '-'}</td><td style="text-align:right">${formatCurrency(t.amount)}</td></tr>`
  ).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 24px; color: #222; font-size: 12px; }
    h1 { font-size: 20px; margin-bottom: 4px; }
    h2 { font-size: 14px; margin-top: 24px; margin-bottom: 8px; color: #555; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
    .subtitle { color: #888; font-size: 13px; margin-bottom: 20px; }
    .summary { display: flex; gap: 32px; margin-bottom: 16px; }
    .summary-item { }
    .summary-label { font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 1px; }
    .summary-value { font-size: 22px; font-weight: 700; color: #6C5CE7; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; padding: 6px 8px; border-bottom: 2px solid #eee; }
    td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; font-size: 11px; }
    .footer { margin-top: 32px; font-size: 10px; color: #aaa; text-align: center; }
  </style></head><body>
    <h1>Expense Report</h1>
    <div class="subtitle">${periodLabel} · Generated ${new Date().toLocaleDateString('en-IN')}</div>
    <div class="summary">
      <div class="summary-item"><div class="summary-label">Total Spent</div><div class="summary-value">${formatCurrency(total)}</div></div>
      <div class="summary-item"><div class="summary-label">Transactions</div><div class="summary-value">${transactions.length}</div></div>
      <div class="summary-item"><div class="summary-label">Average</div><div class="summary-value">${formatCurrency(transactions.length > 0 ? total / transactions.length : 0)}</div></div>
    </div>
    <h2>Category Breakdown</h2>
    <table><tr><th>Category</th><th style="text-align:right">Amount</th><th style="text-align:center">Count</th><th style="text-align:right">%</th></tr>${catRows}</table>
    <h2>All Transactions</h2>
    <table><tr><th>Date</th><th>Description</th><th>Category</th><th style="text-align:right">Amount</th></tr>${txnRows}</table>
    <div class="footer">Generated by Trackk</div>
  </body></html>`;
}

/**
 * Export and share as PDF
 */
export async function sharePDF(transactions: Transaction[], periodLabel: string): Promise<void> {
  const html = generatePDFHTML(transactions, periodLabel);
  const { uri } = await Print.printToFileAsync({ html, base64: false });

  const isAvailable = await Sharing.isAvailableAsync();
  if (isAvailable) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `Trackk Report - ${periodLabel}`,
      UTI: 'com.adobe.pdf',
    });
  } else {
    await Share.share({ message: `Trackk Report saved to: ${uri}` });
  }
}

// ─── Reimbursement Export with Named Receipts ──────────────────────────────

/**
 * Format a date for file naming: 2024-03-15
 */
function formatDateForFilename(timestamp: number): string {
  const d = new Date(timestamp);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

/**
 * Sanitize a merchant name for use as a filename
 */
function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9\s-]/g, '') // Remove special chars
    .replace(/\s+/g, '_')             // Replace spaces with underscores
    .substring(0, 50)                  // Limit length
    || 'Receipt';
}

/**
 * Get file extension from a URI
 */
function getFileExtension(uri: string): string {
  const match = uri.match(/\.([a-zA-Z0-9]+)$/);
  return match ? match[1].toLowerCase() : 'jpg';
}

export interface ReceiptExportItem {
  transaction: Transaction;
  filename: string;
  sourceUri: string;
}

/**
 * Build a list of receipt files with descriptive names.
 * Format: MerchantName_YYYY-MM-DD.ext (e.g., Swiggy_2024-03-15.jpg)
 */
export function buildReceiptExportList(transactions: Transaction[]): ReceiptExportItem[] {
  const withReceipts = transactions.filter(t => t.receiptUri);
  const nameCounts: Record<string, number> = {};

  return withReceipts.map(t => {
    const merchant = t.merchant || t.description || 'Receipt';
    const sanitized = sanitizeFilename(merchant);
    const dateStr = formatDateForFilename(t.timestamp);
    const ext = getFileExtension(t.receiptUri!);

    // Handle duplicate names by appending a counter
    const baseName = `${sanitized}_${dateStr}`;
    nameCounts[baseName] = (nameCounts[baseName] || 0) + 1;
    const suffix = nameCounts[baseName] > 1 ? `_${nameCounts[baseName]}` : '';

    return {
      transaction: t,
      filename: `${baseName}${suffix}.${ext}`,
      sourceUri: t.receiptUri!,
    };
  });
}

/**
 * Export reimbursement receipts as individual named files.
 * Copies receipts to a temp directory with proper names, then shares.
 */
export async function exportReimbursementReceipts(
  transactions: Transaction[],
  tripName?: string,
): Promise<{ success: boolean; count: number; error?: string }> {
  const exportList = buildReceiptExportList(transactions);

  if (exportList.length === 0) {
    return { success: false, count: 0, error: 'No receipts attached to any expenses.' };
  }

  try {
    // Create temp export directory
    const folderName = tripName
      ? sanitizeFilename(tripName) + '_Receipts'
      : 'Trackk_Reimbursement_Receipts';
    const exportDir = `${FileSystem.cacheDirectory}${folderName}/`;

    // Ensure directory exists (clean up old exports first)
    const dirInfo = await FileSystem.getInfoAsync(exportDir);
    if (dirInfo.exists) {
      await FileSystem.deleteAsync(exportDir, { idempotent: true });
    }
    await FileSystem.makeDirectoryAsync(exportDir, { intermediates: true });

    // Copy each receipt with its new name
    for (const item of exportList) {
      const destUri = `${exportDir}${item.filename}`;
      await FileSystem.copyAsync({
        from: item.sourceUri,
        to: destUri,
      });
    }

    // Also generate a summary CSV in the same folder
    const csvContent = generateReimbursementCSV(transactions);
    const csvPath = `${exportDir}Reimbursement_Summary.csv`;
    await FileSystem.writeAsStringAsync(csvPath, csvContent);

    // Share the folder (on iOS this shares individual files)
    // For now, share the CSV summary which references the receipt files
    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      await Sharing.shareAsync(csvPath, {
        mimeType: 'text/csv',
        dialogTitle: `${folderName}`,
        UTI: 'public.comma-separated-values-text',
      });
    } else {
      // Fallback to Share API with text summary
      const summary = generateReimbursementSummary(transactions, exportList);
      await Share.share({
        message: summary,
        title: folderName,
      });
    }

    return { success: true, count: exportList.length };
  } catch (error) {
    return {
      success: false,
      count: 0,
      error: error instanceof Error ? error.message : 'Export failed',
    };
  }
}

/**
 * Generate a CSV specifically for reimbursement with receipt info
 */
function generateReimbursementCSV(transactions: Transaction[]): string {
  const headers = [
    'Date', 'Description', 'Merchant', 'Amount (INR)',
    'Category', 'Receipt Filename', 'Has Receipt',
  ];

  const sorted = [...transactions].sort((a, b) => b.timestamp - a.timestamp);
  const exportList = buildReceiptExportList(transactions);
  const receiptMap = new Map(exportList.map(r => [r.transaction.id, r.filename]));

  const rows = sorted.map(t => [
    formatExportDate(t.timestamp),
    `"${(t.description || '').replace(/"/g, '""')}"`,
    `"${(t.merchant || '').replace(/"/g, '""')}"`,
    t.amount.toFixed(2),
    `"${t.category || ''}"`,
    `"${receiptMap.get(t.id) || ''}"`,
    t.receiptUri ? 'Yes' : 'No',
  ]);

  const total = transactions.reduce((s, t) => s + t.amount, 0);
  rows.push(['', '', 'TOTAL', total.toFixed(2), '', '', '']);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

/**
 * Generate a text summary of reimbursement with receipt filenames
 */
function generateReimbursementSummary(
  transactions: Transaction[],
  exportList: ReceiptExportItem[],
): string {
  const total = transactions.reduce((s, t) => s + t.amount, 0);
  const receiptMap = new Map(exportList.map(r => [r.transaction.id, r.filename]));

  const lines = transactions
    .sort((a, b) => b.timestamp - a.timestamp)
    .map(t => {
      const receipt = receiptMap.get(t.id);
      const receiptLabel = receipt ? ` [Receipt: ${receipt}]` : ' [No receipt]';
      return `  ${formatExportDate(t.timestamp)}  ${formatCurrency(t.amount).padStart(12)}  ${t.merchant || t.description}${receiptLabel}`;
    })
    .join('\n');

  return `TRACKK REIMBURSEMENT EXPORT
${'='.repeat(50)}

Total: ${formatCurrency(total)}
Transactions: ${transactions.length}
Receipts attached: ${exportList.length}

EXPENSES
${'─'.repeat(50)}
${lines}

${'─'.repeat(50)}
Receipt files are named as: MerchantName_YYYY-MM-DD.ext
Generated by Trackk on ${new Date().toLocaleDateString('en-IN')}`;
}
