import { Share } from 'react-native';
import { Transaction } from '../models/types';
import { formatCurrency } from '../utils/helpers';

function formatExportDate(timestamp: number): string {
  const d = new Date(timestamp);
  return d.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Generate CSV content from transactions
 */
export function generateCSV(transactions: Transaction[]): string {
  const headers = ['Date', 'Description', 'Merchant', 'Amount (INR)', 'Category', 'Source', 'Tracker', 'Tags', 'Note'];
  const rows = transactions
    .sort((a, b) => b.timestamp - a.timestamp)
    .map(t => [
      formatExportDate(t.timestamp),
      `"${(t.description || '').replace(/"/g, '""')}"`,
      `"${(t.merchant || '').replace(/"/g, '""')}"`,
      t.amount.toFixed(2),
      `"${t.category || ''}"`,
      `"${t.source || ''}"`,
      t.trackerType,
      `"${(t.tags || []).join(', ')}"`,
      `"${(t.note || '').replace(/"/g, '""')}"`,
    ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

/**
 * Generate a text summary report from transactions
 */
export function generateTextReport(transactions: Transaction[], periodLabel: string): string {
  const total = transactions.reduce((s, t) => s + t.amount, 0);
  const sorted = [...transactions].sort((a, b) => b.timestamp - a.timestamp);

  // Category breakdown
  const cats: Record<string, { amount: number; count: number }> = {};
  for (const t of transactions) {
    const cat = t.category || 'Other';
    if (!cats[cat]) cats[cat] = { amount: 0, count: 0 };
    cats[cat].amount += t.amount;
    cats[cat].count++;
  }

  const catLines = Object.entries(cats)
    .sort((a, b) => b[1].amount - a[1].amount)
    .map(([name, data]) => `  ${name}: ${formatCurrency(data.amount)} (${data.count} transactions)`)
    .join('\n');

  // Top merchants
  const merchants: Record<string, { amount: number; count: number }> = {};
  for (const t of transactions) {
    const m = t.merchant || t.description;
    if (!merchants[m]) merchants[m] = { amount: 0, count: 0 };
    merchants[m].amount += t.amount;
    merchants[m].count++;
  }

  const merchantLines = Object.entries(merchants)
    .sort((a, b) => b[1].amount - a[1].amount)
    .slice(0, 10)
    .map(([name, data], i) => `  ${i + 1}. ${name}: ${formatCurrency(data.amount)} (${data.count}x)`)
    .join('\n');

  return `TRACKK EXPENSE REPORT
${periodLabel}
${'='.repeat(40)}

SUMMARY
  Total Spent: ${formatCurrency(total)}
  Transactions: ${transactions.length}
  Avg per transaction: ${formatCurrency(transactions.length > 0 ? total / transactions.length : 0)}

CATEGORY BREAKDOWN
${catLines || '  No data'}

TOP MERCHANTS
${merchantLines || '  No data'}

TRANSACTIONS
${'─'.repeat(40)}
${sorted.map(t =>
    `  ${formatExportDate(t.timestamp)}  ${formatCurrency(t.amount).padStart(12)}  ${t.description}`
  ).join('\n')}

${'─'.repeat(40)}
Generated by Trackk on ${new Date().toLocaleDateString('en-IN')}`;
}

/**
 * Share CSV data as text
 */
export async function shareCSV(transactions: Transaction[]): Promise<void> {
  const csv = generateCSV(transactions);
  await Share.share({ message: csv, title: 'Trackk Expenses.csv' });
}

/**
 * Share text report
 */
export async function shareTextReport(transactions: Transaction[], periodLabel: string): Promise<void> {
  const report = generateTextReport(transactions, periodLabel);
  await Share.share({ message: report, title: `Trackk Report - ${periodLabel}` });
}
