// Bengali
export default {
  common: { save: 'সেভ', cancel: 'বাতিল', delete: 'মুছুন', edit: 'সম্পাদনা', done: 'হয়ে গেছে', back: 'পিছনে', next: 'পরবর্তী', ok: 'ঠিক আছে', yes: 'হ্যাঁ', no: 'না', loading: 'লোড হচ্ছে...', error: 'ত্রুটি', success: 'সফল', retry: 'আবার চেষ্টা', search: 'খুঁজুন', add: 'যোগ করুন', remove: 'সরান', share: 'শেয়ার', settings: 'সেটিংস', today: 'আজ', yesterday: 'গতকাল', thisWeek: 'এই সপ্তাহ', earlier: 'আগে' },
  tabs: { home: 'হোম', personal: 'ব্যক্তিগত', groups: 'গ্রুপ', insights: 'ইনসাইট', profile: 'প্রোফাইল' },
  home: { greeting: '{{timeOfDay}}, {{name}}', morning: 'সুপ্রভাত', afternoon: 'নমস্কার', evening: 'শুভ সন্ধ্যা', todaySpend: 'আজকের খরচ', monthSpend: 'এই মাস', quickAdd: 'দ্রুত যোগ', reviewExpenses: 'খরচ দেখুন', noTransactions: 'এখনো কোনো লেনদেন নেই', startTracking: 'আপনার খরচ ট্র্যাক করা শুরু করুন' },
  groups: { title: 'গ্রুপ', newGroup: 'নতুন গ্রুপ', noGroups: 'এখনো কোনো গ্রুপ নেই', createFirst: 'বন্ধুদের সাথে খরচ ভাগ করতে গ্রুপ তৈরি করুন', allSettled: 'সব সেটল হয়ে গেছে', youOwe: 'আপনাকে {{amount}} দিতে হবে', youAreOwed: 'আপনার {{amount}} পাওনা আছে', settleUp: 'সেটল করুন', addExpense: 'খরচ যোগ করুন', expenses: '{{count}} খরচ', trackGroup: 'এই গ্রুপ ট্র্যাক করুন', trackGroupSub: 'পেমেন্ট স্বয়ংক্রিয়ভাবে ধরুন এবং সমানভাবে ভাগ করুন' },
  split: { amount: 'পরিমাণ', description: 'বিবরণ', descriptionPlaceholder: 'যেমন: BBQ Nation এ ডিনার...', addNote: 'নোট যোগ করুন', notePlaceholder: 'প্রসঙ্গের জন্য নোট...', category: 'বিভাগ', splitType: 'ভাগের ধরন', equal: 'সমান', byAmount: 'পরিমাণ অনুসারে', whosIn: 'কে কে আছেন?', selectedOf: '{{total}} এর মধ্যে {{selected}} নির্বাচিত', each: 'প্রত্যেকে {{amount}}', confirmSplit: 'স্প্লিট নিশ্চিত করুন', splitWays: '{{count}} জনে ভাগ', addGuest: 'অতিথি যোগ করুন', guestHint: 'একবারের জন্য, সদস্যের সাথে ট্যাগ করা', noteOptional: 'নোট (ঐচ্ছিক)' },
  settle: { selectBalance: 'সেটল করতে ব্যালেন্স বেছে নিন', settlePayment: 'পেমেন্ট সেটল', payTo: '{{name}} কে পেমেন্ট', totalDebt: 'মোট বাকি', settleAmount: 'সেটল পরিমাণ', fullSettlement: 'পূর্ণ সেটলমেন্ট', partial: 'আংশিক · বাকি: {{amount}}', payUPI: 'UPI / কার্ড দিয়ে', opensPaymentApp: 'আপনার পেমেন্ট অ্যাপ খুলবে', settledByCash: 'ক্যাশে সেটল', markAsPaid: 'ক্যাশে পেমেন্ট হয়েছে', wasPaymentDone: 'পেমেন্ট হয়েছে?', yesPaymentDone: 'হ্যাঁ, হয়ে গেছে', markAsSettled: 'সেটল হিসেবে চিহ্নিত করুন', noPaymentFailed: 'না, হয়নি', dontMark: 'চিহ্নিত করবেন না' },
  profile: { title: 'প্রোফাইল', editName: 'পরিবর্তন করতে ট্যাপ করুন', verified: 'যাচাইকৃত', subscription: 'সাবস্ক্রিপশন', referEarn: 'রেফার ও আয়', emailDetection: 'ইমেইল লেনদেন শনাক্তকরণ', emailPrivacy: 'আপনি অনুমতি দিলেই আমরা আপনার ইমেইল সংযোগ করি।', connect: 'সংযোগ', disconnect: 'সংযোগ বিচ্ছিন্ন', notConnected: 'সংযুক্ত নয়', privacy: 'গোপনীয়তা ও ডেটা', dataSafe: 'আপনার ডেটা নিরাপদ', privacyDesc: 'Trackk ইভেন্ট-ড্রিভেন SMS শনাক্তকরণ ব্যবহার করে।', about: 'সম্পর্কে', appVersion: 'অ্যাপ ভার্সন', signOut: 'সাইন আউট', signOutConfirm: 'সাইন আউট করতে চান?', language: 'ভাষা', currency: 'মুদ্রা' },
  insights: { title: 'ইনসাইট', thisMonth: 'এই মাস', allTime: 'সব সময়', topCategories: 'শীর্ষ বিভাগ', recurring: 'পুনরাবৃত্ত পেমেন্ট', trends: 'খরচের ট্রেন্ড' },
  goals: { title: 'সঞ্চয় লক্ষ্য', newGoal: 'নতুন লক্ষ্য', dailyBudget: 'দৈনিক বাজেট', streak: 'স্ট্রিক', saved: 'সঞ্চয়', target: 'লক্ষ্য' },
  trackers: { subscriptions: 'সাবস্ক্রিপশন', investments: 'বিনিয়োগ', emis: 'EMI ও ঋণ', sync: 'সিংক', monthly: 'মাসিক', yearly: 'বার্ষিক', active: 'সক্রিয়', noItems: 'কিছু পাওয়া যায়নি', scanTip: 'আপনার SMS এবং ইমেইল থেকে {{type}} খুঁজব' },
  reminders: { title: 'সেটলমেন্ট রিমাইন্ডার', gentle1: '{{name}} এ {{amount}} বাকি আছে', gentle2: 'রিমাইন্ডার: {{name}} এ {{amount}} বাকি। তাড়াহুড়ো নেই!', gentle3: '{{name}} এ {{amount}} সেটল হয়নি', gentle4: 'বন্ধুত্বপূর্ণ রিমাইন্ডার: {{name}} এ {{amount}} বাকি' },
  currency: { title: 'মুদ্রা', searchPlaceholder: 'মুদ্রা খুঁজুন...' },
};
