// German
export default {
  common: { save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', done: 'Fertig', back: 'Zurück', next: 'Weiter', ok: 'OK', yes: 'Ja', no: 'Nein', loading: 'Laden...', error: 'Fehler', success: 'Erfolg', retry: 'Erneut versuchen', search: 'Suchen', add: 'Hinzufügen', remove: 'Entfernen', share: 'Teilen', settings: 'Einstellungen', today: 'Heute', yesterday: 'Gestern', thisWeek: 'Diese Woche', earlier: 'Früher' },
  tabs: { home: 'Start', personal: 'Persönlich', groups: 'Gruppen', insights: 'Analysen', profile: 'Profil' },
  home: { greeting: '{{timeOfDay}}, {{name}}', morning: 'Guten Morgen', afternoon: 'Guten Tag', evening: 'Guten Abend', todaySpend: 'Heutige Ausgaben', monthSpend: 'Diesen Monat', quickAdd: 'Schnell hinzufügen', reviewExpenses: 'Ausgaben prüfen', noTransactions: 'Noch keine Transaktionen', startTracking: 'Beginnen Sie Ihre Ausgaben zu verfolgen' },
  groups: { title: 'Gruppen', newGroup: 'Neue Gruppe', noGroups: 'Noch keine Gruppen', createFirst: 'Erstellen Sie eine Gruppe um Ausgaben zu teilen', allSettled: 'Alles beglichen', youOwe: 'Sie schulden {{amount}}', youAreOwed: 'Ihnen werden {{amount}} geschuldet', settleUp: 'Begleichen', addExpense: 'Ausgabe hinzufügen', expenses: '{{count}} Ausgaben', trackGroup: 'Diese Gruppe verfolgen', trackGroupSub: 'Zahlungen automatisch erkennen und gleichmäßig teilen' },
  split: { amount: 'Betrag', description: 'Beschreibung', descriptionPlaceholder: 'Z.B.: Abendessen, Einkäufe...', addNote: 'Notiz hinzufügen', notePlaceholder: 'Notiz für Kontext hinzufügen...', category: 'Kategorie', splitType: 'Aufteilungsart', equal: 'Gleich', byAmount: 'Nach Betrag', whosIn: 'Wer ist dabei?', selectedOf: '{{selected}} von {{total}} ausgewählt', each: '{{amount}} pro Person', confirmSplit: 'Aufteilung bestätigen', splitWays: 'auf {{count}} aufteilen', addGuest: 'Gast hinzufügen', guestHint: 'Einmalig, einem Mitglied zugeordnet', noteOptional: 'Notiz (Optional)' },
  settle: { selectBalance: 'Saldo zum Begleichen auswählen', settlePayment: 'Zahlung begleichen', payTo: 'Zahlung an {{name}}', totalDebt: 'Gesamtschuld', settleAmount: 'Betrag begleichen', fullSettlement: 'Vollständige Begleichung', partial: 'Teilweise · Rest: {{amount}}', payUPI: 'Per UPI / Karte zahlen', opensPaymentApp: 'Öffnet Ihre Zahlungs-App', settledByCash: 'Bar beglichen', markAsPaid: 'Als bar bezahlt markieren', wasPaymentDone: 'Wurde die Zahlung durchgeführt?', yesPaymentDone: 'Ja, Zahlung erfolgt', markAsSettled: 'Als beglichen markieren', noPaymentFailed: 'Nein, Zahlung fehlgeschlagen', dontMark: 'Nicht markieren' },
  profile: { title: 'Profil', editName: 'zum Bearbeiten tippen', verified: 'Verifiziert', subscription: 'Abonnement', referEarn: 'Empfehlen & verdienen', emailDetection: 'E-Mail-Erkennung', emailPrivacy: 'Wir verbinden Ihre E-Mail nur mit Ihrer Erlaubnis.', connect: 'Verbinden', disconnect: 'Trennen', notConnected: 'Nicht verbunden', privacy: 'Datenschutz', dataSafe: 'Ihre Daten sind sicher', privacyDesc: 'Trackk verwendet ereignisgesteuerte SMS-Erkennung.', about: 'Über', appVersion: 'App-Version', signOut: 'Abmelden', signOutConfirm: 'Möchten Sie sich abmelden?', language: 'Sprache', currency: 'Währung' },
  insights: { title: 'Analysen', thisMonth: 'Diesen Monat', allTime: 'Gesamt', topCategories: 'Top-Kategorien', recurring: 'Wiederkehrende Zahlungen', trends: 'Ausgabentrends' },
  goals: { title: 'Sparziele', newGoal: 'Neues Ziel', dailyBudget: 'Tagesbudget', streak: 'Serie', saved: 'Gespart', target: 'Ziel' },
  trackers: { subscriptions: 'Abonnements', investments: 'Investitionen', emis: 'Raten & Kredite', sync: 'Synchronisieren', monthly: 'Monatlich', yearly: 'Jährlich', active: 'Aktiv', noItems: 'Keine Einträge gefunden', scanTip: 'Wir suchen {{type}} in Ihren SMS und E-Mails' },
  reminders: { title: 'Zahlungserinnerung', gentle1: '{{amount}} ausstehend bei {{name}}', gentle2: 'Erinnerung: {{amount}} offen bei {{name}}. Kein Stress!', gentle3: '{{name}} hat {{amount}} unbeglichen', gentle4: 'Freundliche Erinnerung: {{amount}} offen bei {{name}}' },
  currency: { title: 'Währung', searchPlaceholder: 'Währungen suchen...' },
};
