// Spanish
export default {
  common: { save: 'Guardar', cancel: 'Cancelar', delete: 'Eliminar', edit: 'Editar', done: 'Hecho', back: 'Atrás', next: 'Siguiente', ok: 'OK', yes: 'Sí', no: 'No', loading: 'Cargando...', error: 'Error', success: 'Éxito', retry: 'Reintentar', search: 'Buscar', add: 'Agregar', remove: 'Eliminar', share: 'Compartir', settings: 'Configuración', today: 'Hoy', yesterday: 'Ayer', thisWeek: 'Esta semana', earlier: 'Antes' },
  tabs: { home: 'Inicio', personal: 'Personal', groups: 'Grupos', insights: 'Análisis', profile: 'Perfil' },
  home: { greeting: '{{timeOfDay}}, {{name}}', morning: 'Buenos días', afternoon: 'Buenas tardes', evening: 'Buenas noches', todaySpend: 'Gasto de hoy', monthSpend: 'Este mes', quickAdd: 'Agregar rápido', reviewExpenses: 'Revisar gastos', noTransactions: 'Sin transacciones aún', startTracking: 'Comienza a rastrear tus gastos' },
  groups: { title: 'Grupos', newGroup: 'Nuevo grupo', noGroups: 'Sin grupos aún', createFirst: 'Crea un grupo para dividir gastos con amigos', allSettled: 'Todo liquidado', youOwe: 'Debes {{amount}}', youAreOwed: 'Te deben {{amount}}', settleUp: 'Liquidar', addExpense: 'Agregar gasto', expenses: '{{count}} gastos', trackGroup: 'Rastrear este grupo', trackGroupSub: 'Detectar pagos automáticamente y dividir equitativamente' },
  split: { amount: 'Monto', description: 'Descripción', descriptionPlaceholder: 'Ej: Cena, Supermercado...', addNote: 'Agregar nota', notePlaceholder: 'Agrega una nota para contexto...', category: 'Categoría', splitType: 'Tipo de división', equal: 'Igual', byAmount: 'Por monto', whosIn: '¿Quién participa?', selectedOf: '{{selected}} de {{total}} seleccionados', each: '{{amount}} cada uno', confirmSplit: 'Confirmar división', splitWays: 'dividir entre {{count}}', addGuest: 'Agregar invitado', guestHint: 'Una vez, etiquetado a un miembro', noteOptional: 'Nota (Opcional)' },
  settle: { selectBalance: 'Selecciona un saldo para liquidar', settlePayment: 'Liquidar pago', payTo: 'Pagar a {{name}}', totalDebt: 'Deuda total', settleAmount: 'Monto a liquidar', fullSettlement: 'Liquidación total', partial: 'Parcial · Restante: {{amount}}', payUPI: 'Pagar vía UPI / Tarjeta', opensPaymentApp: 'Abre tu app de pago', settledByCash: 'Liquidado en efectivo', markAsPaid: 'Marcar como pagado en efectivo', wasPaymentDone: '¿Se realizó el pago?', yesPaymentDone: 'Sí, se realizó', markAsSettled: 'Marcar como liquidado', noPaymentFailed: 'No, falló el pago', dontMark: 'No marcar como liquidado' },
  profile: { title: 'Perfil', editName: 'toca para editar', verified: 'Verificado', subscription: 'Suscripción', referEarn: 'Refiere y gana', emailDetection: 'Detección de email', emailPrivacy: 'Solo conectamos tu email si lo permites.', connect: 'Conectar', disconnect: 'Desconectar', notConnected: 'No conectado', privacy: 'Privacidad y datos', dataSafe: 'Tus datos están seguros', privacyDesc: 'Trackk usa detección de SMS basada en eventos.', about: 'Acerca de', appVersion: 'Versión', signOut: 'Cerrar sesión', signOutConfirm: '¿Quieres cerrar sesión?', language: 'Idioma', currency: 'Moneda' },
  insights: { title: 'Análisis', thisMonth: 'Este mes', allTime: 'Todo el tiempo', topCategories: 'Categorías principales', recurring: 'Pagos recurrentes', trends: 'Tendencias de gasto' },
  goals: { title: 'Metas de ahorro', newGoal: 'Nueva meta', dailyBudget: 'Presupuesto diario', streak: 'Racha', saved: 'Ahorrado', target: 'Meta' },
  trackers: { subscriptions: 'Suscripciones', investments: 'Inversiones', emis: 'Cuotas y préstamos', sync: 'Sincronizar', monthly: 'Mensual', yearly: 'Anual', active: 'Activo', noItems: 'No se encontraron elementos', scanTip: 'Buscaremos {{type}} en tu SMS y email' },
  reminders: { title: 'Recordatorio de pago', gentle1: 'Tienes {{amount}} pendiente con {{name}}', gentle2: 'Recordatorio: {{amount}} pendiente en {{name}}. ¡Sin prisa!', gentle3: '{{name}} tiene {{amount}} sin liquidar', gentle4: 'Recordatorio amigable: {{amount}} pendiente en {{name}}' },
  currency: { title: 'Moneda', searchPlaceholder: 'Buscar monedas...' },
};
