// French
export default {
  common: { save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', done: 'Terminé', back: 'Retour', next: 'Suivant', ok: 'OK', yes: 'Oui', no: 'Non', loading: 'Chargement...', error: 'Erreur', success: 'Succès', retry: 'Réessayer', search: 'Rechercher', add: 'Ajouter', remove: 'Supprimer', share: 'Partager', settings: 'Paramètres', today: "Aujourd'hui", yesterday: 'Hier', thisWeek: 'Cette semaine', earlier: 'Plus tôt' },
  tabs: { home: 'Accueil', personal: 'Personnel', groups: 'Groupes', insights: 'Analyses', profile: 'Profil' },
  home: { greeting: '{{timeOfDay}}, {{name}}', morning: 'Bonjour', afternoon: 'Bon après-midi', evening: 'Bonsoir', todaySpend: "Dépenses d'aujourd'hui", monthSpend: 'Ce mois', quickAdd: 'Ajout rapide', reviewExpenses: 'Revoir les dépenses', noTransactions: 'Pas encore de transactions', startTracking: 'Commencez à suivre vos dépenses' },
  groups: { title: 'Groupes', newGroup: 'Nouveau groupe', noGroups: 'Pas encore de groupes', createFirst: 'Créez un groupe pour partager les dépenses', allSettled: 'Tout est réglé', youOwe: 'Vous devez {{amount}}', youAreOwed: 'On vous doit {{amount}}', settleUp: 'Régler', addExpense: 'Ajouter une dépense', expenses: '{{count}} dépenses', trackGroup: 'Suivre ce groupe', trackGroupSub: 'Détecter les paiements et partager équitablement' },
  split: { amount: 'Montant', description: 'Description', descriptionPlaceholder: 'Ex: Dîner, Courses...', addNote: 'Ajouter une note', notePlaceholder: 'Ajoutez une note...', category: 'Catégorie', splitType: 'Type de partage', equal: 'Égal', byAmount: 'Par montant', whosIn: 'Qui participe?', selectedOf: '{{selected}} sur {{total}} sélectionnés', each: '{{amount}} chacun', confirmSplit: 'Confirmer le partage', splitWays: 'partager entre {{count}}', addGuest: 'Ajouter un invité', guestHint: 'Une fois, lié à un membre', noteOptional: 'Note (Optionnel)' },
  settle: { selectBalance: 'Sélectionnez un solde à régler', settlePayment: 'Régler le paiement', payTo: 'Payer à {{name}}', totalDebt: 'Dette totale', settleAmount: 'Montant à régler', fullSettlement: 'Règlement complet', partial: 'Partiel · Restant: {{amount}}', payUPI: 'Payer via UPI / Carte', opensPaymentApp: 'Ouvre votre app de paiement', settledByCash: 'Réglé en espèces', markAsPaid: 'Marquer comme payé en espèces', wasPaymentDone: 'Le paiement a-t-il été effectué?', yesPaymentDone: 'Oui, paiement effectué', markAsSettled: 'Marquer comme réglé', noPaymentFailed: 'Non, le paiement a échoué', dontMark: 'Ne pas marquer' },
  profile: { title: 'Profil', editName: 'appuyez pour modifier', verified: 'Vérifié', subscription: 'Abonnement', referEarn: 'Parrainage', emailDetection: 'Détection email', emailPrivacy: 'Nous connectons votre email uniquement avec votre permission.', connect: 'Connecter', disconnect: 'Déconnecter', notConnected: 'Non connecté', privacy: 'Confidentialité', dataSafe: 'Vos données sont en sécurité', privacyDesc: 'Trackk utilise la détection SMS événementielle.', about: 'À propos', appVersion: 'Version', signOut: 'Déconnexion', signOutConfirm: 'Voulez-vous vous déconnecter?', language: 'Langue', currency: 'Devise' },
  insights: { title: 'Analyses', thisMonth: 'Ce mois', allTime: 'Tout temps', topCategories: 'Catégories principales', recurring: 'Paiements récurrents', trends: 'Tendances' },
  goals: { title: "Objectifs d'épargne", newGoal: 'Nouvel objectif', dailyBudget: 'Budget quotidien', streak: 'Série', saved: 'Épargné', target: 'Objectif' },
  trackers: { subscriptions: 'Abonnements', investments: 'Investissements', emis: 'Mensualités et prêts', sync: 'Synchroniser', monthly: 'Mensuel', yearly: 'Annuel', active: 'Actif', noItems: 'Aucun élément trouvé', scanTip: 'Nous rechercherons {{type}} dans vos SMS et emails' },
  reminders: { title: 'Rappel de règlement', gentle1: 'Vous avez {{amount}} en attente avec {{name}}', gentle2: 'Rappel: {{amount}} en attente dans {{name}}. Pas de pression!', gentle3: '{{name}} a {{amount}} non réglé', gentle4: 'Rappel amical: {{amount}} en attente dans {{name}}' },
  currency: { title: 'Devise', searchPlaceholder: 'Rechercher des devises...' },
};
