// Kannada
export default {
  common: { save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದು', delete: 'ಅಳಿಸಿ', edit: 'ಸಂಪಾದಿಸಿ', done: 'ಮುಗಿಯಿತು', back: 'ಹಿಂದೆ', next: 'ಮುಂದೆ', ok: 'ಸರಿ', yes: 'ಹೌದು', no: 'ಇಲ್ಲ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', error: 'ದೋಷ', success: 'ಯಶಸ್ವಿ', retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ', search: 'ಹುಡುಕಿ', add: 'ಸೇರಿಸಿ', remove: 'ತೆಗೆಯಿರಿ', share: 'ಹಂಚಿಕೊಳ್ಳಿ', settings: 'ಸೆಟ್ಟಿಂಗ್ಸ್', today: 'ಇಂದು', yesterday: 'ನಿನ್ನೆ', thisWeek: 'ಈ ವಾರ', earlier: 'ಮೊದಲು' },
  tabs: { home: 'ಮುಖಪುಟ', personal: 'ವೈಯಕ್ತಿಕ', groups: 'ಗುಂಪುಗಳು', insights: 'ಒಳನೋಟ', profile: 'ಪ್ರೊಫೈಲ್' },
  home: { greeting: '{{timeOfDay}}, {{name}}', morning: 'ಶುಭೋದಯ', afternoon: 'ನಮಸ್ಕಾರ', evening: 'ಶುಭ ಸಂಜೆ', todaySpend: 'ಇಂದಿನ ಖರ್ಚು', monthSpend: 'ಈ ತಿಂಗಳು', quickAdd: 'ತ್ವರಿತ ಸೇರ್ಪಡೆ', reviewExpenses: 'ಖರ್ಚುಗಳನ್ನು ನೋಡಿ', noTransactions: 'ಇನ್ನೂ ವಹಿವಾಟುಗಳಿಲ್ಲ', startTracking: 'ನಿಮ್ಮ ಖರ್ಚುಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಿ' },
  groups: { title: 'ಗುಂಪುಗಳು', newGroup: 'ಹೊಸ ಗುಂಪು', noGroups: 'ಇನ್ನೂ ಗುಂಪುಗಳಿಲ್ಲ', createFirst: 'ಸ್ನೇಹಿತರೊಂದಿಗೆ ಖರ್ಚುಗಳನ್ನು ಹಂಚಲು ಗುಂಪು ರಚಿಸಿ', allSettled: 'ಎಲ್ಲಾ ಸೆಟಲ್ ಆಯಿತು', youOwe: 'ನೀವು {{amount}} ಕೊಡಬೇಕು', youAreOwed: 'ನಿಮಗೆ {{amount}} ಬರಬೇಕು', settleUp: 'ಸೆಟಲ್ ಮಾಡಿ', addExpense: 'ಖರ್ಚು ಸೇರಿಸಿ', expenses: '{{count}} ಖರ್ಚುಗಳು', trackGroup: 'ಈ ಗುಂಪನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ', trackGroupSub: 'ಪಾವತಿಗಳನ್ನು ಸ್ವಯಂ ಗುರುತಿಸಿ ಸಮನಾಗಿ ಹಂಚಿ' },
  split: { amount: 'ಮೊತ್ತ', description: 'ವಿವರಣೆ', descriptionPlaceholder: 'ಉದಾ: BBQ Nation ನಲ್ಲಿ ಊಟ...', addNote: 'ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ', notePlaceholder: 'ಸಂದರ್ಭಕ್ಕಾಗಿ ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ...', category: 'ವರ್ಗ', splitType: 'ಹಂಚಿಕೆ ವಿಧ', equal: 'ಸಮ', byAmount: 'ಮೊತ್ತದಿಂದ', whosIn: 'ಯಾರ್ಯಾರು?', selectedOf: '{{total}} ರಲ್ಲಿ {{selected}} ಆಯ್ಕೆ', each: 'ಪ್ರತಿಯೊಬ್ಬರಿಗೂ {{amount}}', confirmSplit: 'ಸ್ಪ್ಲಿಟ್ ದೃಢೀಕರಿಸಿ', splitWays: '{{count}} ಜನರಲ್ಲಿ ಹಂಚಿ', addGuest: 'ಅತಿಥಿ ಸೇರಿಸಿ', guestHint: 'ಒಂದು ಬಾರಿ, ಸದಸ್ಯರಿಗೆ ಟ್ಯಾಗ್', noteOptional: 'ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)' },
  settle: { selectBalance: 'ಸೆಟಲ್ ಮಾಡಲು ಬ್ಯಾಲೆನ್ಸ್ ಆಯ್ಕೆ ಮಾಡಿ', settlePayment: 'ಪಾವತಿ ಸೆಟಲ್', payTo: '{{name}} ಗೆ ಪಾವತಿ', totalDebt: 'ಒಟ್ಟು ಬಾಕಿ', settleAmount: 'ಸೆಟಲ್ ಮೊತ್ತ', fullSettlement: 'ಪೂರ್ಣ ಸೆಟಲ್‌ಮೆಂಟ್', partial: 'ಭಾಗಶಃ · ಉಳಿದಿದೆ: {{amount}}', payUPI: 'UPI / ಕಾರ್ಡ್ ಮೂಲಕ', opensPaymentApp: 'ನಿಮ್ಮ ಪೇಮೆಂಟ್ ಆ್ಯಪ್ ತೆರೆಯುತ್ತದೆ', settledByCash: 'ನಗದಿನಲ್ಲಿ ಸೆಟಲ್', markAsPaid: 'ನಗದಿನಲ್ಲಿ ಪಾವತಿಸಿದೆ ಎಂದು ಗುರುತಿಸಿ', wasPaymentDone: 'ಪಾವತಿ ಆಯಿತಾ?', yesPaymentDone: 'ಹೌದು, ಆಯಿತು', markAsSettled: 'ಸೆಟಲ್ ಆಗಿದೆ ಎಂದು ಗುರುತಿಸಿ', noPaymentFailed: 'ಇಲ್ಲ, ಆಗಿಲ್ಲ', dontMark: 'ಗುರುತಿಸಬೇಡಿ' },
  profile: { title: 'ಪ್ರೊಫೈಲ್', editName: 'ಬದಲಾಯಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ', verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', subscription: 'ಸಬ್ಸ್ಕ್ರಿಪ್ಷನ್', referEarn: 'ರೆಫರ್ & ಗಳಿಸಿ', emailDetection: 'ಇಮೇಲ್ ವಹಿವಾಟು ಪತ್ತೆ', emailPrivacy: 'ನೀವು ಅನುಮತಿಸಿದರೆ ಮಾತ್ರ ನಿಮ್ಮ ಇಮೇಲ್ ಅನ್ನು ಕನೆಕ್ಟ್ ಮಾಡುತ್ತೇವೆ.', connect: 'ಕನೆಕ್ಟ್', disconnect: 'ಡಿಸ್ಕನೆಕ್ಟ್', notConnected: 'ಕನೆಕ್ಟ್ ಆಗಿಲ್ಲ', privacy: 'ಗೌಪ್ಯತೆ & ಡೇಟಾ', dataSafe: 'ನಿಮ್ಮ ಡೇಟಾ ಸುರಕ್ಷಿತ', privacyDesc: 'Trackk ಈವೆಂಟ್-ಡ್ರಿವನ್ SMS ಪತ್ತೆಯನ್ನು ಬಳಸುತ್ತದೆ.', about: 'ಬಗ್ಗೆ', appVersion: 'ಆ್ಯಪ್ ಆವೃತ್ತಿ', signOut: 'ಸೈನ್ ಔಟ್', signOutConfirm: 'ಸೈನ್ ಔಟ್ ಮಾಡಬೇಕೇ?', language: 'ಭಾಷೆ', currency: 'ಕರೆನ್ಸಿ' },
  insights: { title: 'ಒಳನೋಟ', thisMonth: 'ಈ ತಿಂಗಳು', allTime: 'ಎಲ್ಲಾ ಸಮಯ', topCategories: 'ಟಾಪ್ ವರ್ಗಗಳು', recurring: 'ಪುನರಾವರ್ತಿತ ಪಾವತಿಗಳು', trends: 'ಖರ್ಚು ಟ್ರೆಂಡ್ಸ್' },
  goals: { title: 'ಉಳಿತಾಯ ಗುರಿಗಳು', newGoal: 'ಹೊಸ ಗುರಿ', dailyBudget: 'ದೈನಂದಿನ ಬಜೆಟ್', streak: 'ಸ್ಟ್ರೀಕ್', saved: 'ಉಳಿತಾಯ', target: 'ಗುರಿ' },
  trackers: { subscriptions: 'ಸಬ್ಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು', investments: 'ಹೂಡಿಕೆಗಳು', emis: 'EMI & ಸಾಲಗಳು', sync: 'ಸಿಂಕ್', monthly: 'ಮಾಸಿಕ', yearly: 'ವಾರ್ಷಿಕ', active: 'ಸಕ್ರಿಯ', noItems: 'ಏನೂ ಸಿಗಲಿಲ್ಲ', scanTip: 'ನಿಮ್ಮ SMS ಮತ್ತು ಇಮೇಲ್‌ನಿಂದ {{type}} ಹುಡುಕುತ್ತೇವೆ' },
  reminders: { title: 'ಸೆಟಲ್‌ಮೆಂಟ್ ನೆನಪೊಲೆ', gentle1: '{{name}} ನಲ್ಲಿ {{amount}} ಬಾಕಿ ಇದೆ', gentle2: 'ನೆನಪೊಲೆ: {{name}} ನಲ್ಲಿ {{amount}} ಬಾಕಿ. ಅವಸರವಿಲ್ಲ!', gentle3: '{{name}} ನಲ್ಲಿ {{amount}} ಸೆಟಲ್ ಆಗಿಲ್ಲ', gentle4: 'ಸ್ನೇಹಪರ ನೆನಪೊಲೆ: {{name}} ನಲ್ಲಿ {{amount}} ಬಾಕಿ' },
  currency: { title: 'ಕರೆನ್ಸಿ', searchPlaceholder: 'ಕರೆನ್ಸಿ ಹುಡುಕಿ...' },
};
