// Marathi
export default {
  common: { save: 'सेव्ह करा', cancel: 'रद्द करा', delete: 'हटवा', edit: 'संपादित करा', done: 'झाले', back: 'मागे', next: 'पुढे', ok: 'ठीक', yes: 'हो', no: 'नाही', loading: 'लोड होत आहे...', error: 'त्रुटी', success: 'यशस्वी', retry: 'पुन्हा प्रयत्न करा', search: 'शोधा', add: 'जोडा', remove: 'काढा', share: 'शेअर करा', settings: 'सेटिंग्ज', today: 'आज', yesterday: 'काल', thisWeek: 'या आठवड्यात', earlier: 'आधी' },
  tabs: { home: 'होम', personal: 'वैयक्तिक', groups: 'गट', insights: 'इनसाइट्स', profile: 'प्रोफाइल' },
  home: { greeting: '{{timeOfDay}}, {{name}}', morning: 'सुप्रभात', afternoon: 'नमस्कार', evening: 'शुभ संध्याकाळ', todaySpend: 'आजचा खर्च', monthSpend: 'या महिन्यात', quickAdd: 'त्वरित जोडा', reviewExpenses: 'खर्च पहा', noTransactions: 'अजून कोणतेही व्यवहार नाहीत', startTracking: 'तुमचा खर्च ट्रॅक करायला सुरुवात करा' },
  groups: { title: 'गट', newGroup: 'नवीन गट', noGroups: 'अजून कोणतेही गट नाहीत', createFirst: 'मित्रांसोबत खर्च वाटण्यासाठी गट तयार करा', allSettled: 'सर्व सेटल झाले', youOwe: 'तुम्हाला {{amount}} द्यायचे आहे', youAreOwed: 'तुम्हाला {{amount}} मिळायचे आहे', settleUp: 'सेटल करा', addExpense: 'खर्च जोडा', expenses: '{{count}} खर्च', trackGroup: 'हा गट ट्रॅक करा', trackGroupSub: 'पेमेंट आपोआप ओळखा आणि समान वाटा' },
  split: { amount: 'रक्कम', description: 'वर्णन', descriptionPlaceholder: 'उदा: BBQ Nation ला जेवण...', addNote: 'नोट जोडा', notePlaceholder: 'संदर्भासाठी नोट जोडा...', category: 'श्रेणी', splitType: 'वाटणी प्रकार', equal: 'समान', byAmount: 'रकमेनुसार', whosIn: 'कोण कोण?', selectedOf: '{{total}} पैकी {{selected}} निवडले', each: 'प्रत्येकी {{amount}}', confirmSplit: 'स्प्लिट कन्फर्म करा', splitWays: '{{count}} जणांमध्ये वाटा', addGuest: 'पाहुणा जोडा', guestHint: 'एकदाच, सदस्याला टॅग केलेले', noteOptional: 'नोट (पर्यायी)' },
  settle: { selectBalance: 'सेटल करण्यासाठी बॅलन्स निवडा', settlePayment: 'पेमेंट सेटल करा', payTo: '{{name}} ला पेमेंट', totalDebt: 'एकूण बाकी', settleAmount: 'सेटल रक्कम', fullSettlement: 'पूर्ण सेटलमेंट', partial: 'अंशतः · बाकी: {{amount}}', payUPI: 'UPI / कार्डद्वारे', opensPaymentApp: 'तुमचे पेमेंट ऍप उघडेल', settledByCash: 'रोखीत सेटल', markAsPaid: 'रोखीत भरले असे चिन्हांकित करा', wasPaymentDone: 'पेमेंट झाले का?', yesPaymentDone: 'हो, झाले', markAsSettled: 'सेटल झाले असे चिन्हांकित करा', noPaymentFailed: 'नाही, झाले नाही', dontMark: 'चिन्हांकित करू नका' },
  profile: { title: 'प्रोफाइल', editName: 'बदलण्यासाठी टॅप करा', verified: 'सत्यापित', subscription: 'सबस्क्रिप्शन', referEarn: 'रेफर करा आणि कमवा', emailDetection: 'ईमेल व्यवहार शोध', emailPrivacy: 'तुम्ही परवानगी दिल्यासच आम्ही तुमचे ईमेल जोडतो.', connect: 'जोडा', disconnect: 'डिस्कनेक्ट', notConnected: 'जोडलेले नाही', privacy: 'गोपनीयता आणि डेटा', dataSafe: 'तुमचा डेटा सुरक्षित आहे', privacyDesc: 'Trackk इव्हेंट-ड्रिव्हन SMS शोध वापरते.', about: 'विषयी', appVersion: 'ऍप आवृत्ती', signOut: 'साइन आउट', signOutConfirm: 'साइन आउट करायचे आहे का?', language: 'भाषा', currency: 'चलन' },
  insights: { title: 'इनसाइट्स', thisMonth: 'या महिन्यात', allTime: 'सर्व काळ', topCategories: 'शीर्ष श्रेण्या', recurring: 'वारंवार होणारी पेमेंट्स', trends: 'खर्चाचे ट्रेंड्स' },
  goals: { title: 'बचत उद्दिष्टे', newGoal: 'नवीन उद्दिष्ट', dailyBudget: 'दैनंदिन बजेट', streak: 'स्ट्रीक', saved: 'बचत', target: 'उद्दिष्ट' },
  trackers: { subscriptions: 'सबस्क्रिप्शन्स', investments: 'गुंतवणूक', emis: 'EMI आणि कर्ज', sync: 'सिंक', monthly: 'मासिक', yearly: 'वार्षिक', active: 'सक्रिय', noItems: 'काहीही सापडले नाही', scanTip: 'तुमच्या SMS आणि ईमेलमधून {{type}} शोधू' },
  reminders: { title: 'सेटलमेंट स्मरणपत्र', gentle1: '{{name}} मध्ये {{amount}} बाकी आहे', gentle2: 'स्मरणपत्र: {{name}} मध्ये {{amount}} बाकी. घाई नाही!', gentle3: '{{name}} मध्ये {{amount}} सेटल झालेले नाही', gentle4: 'मैत्रीपूर्ण स्मरणपत्र: {{name}} मध्ये {{amount}} बाकी' },
  currency: { title: 'चलन', searchPlaceholder: 'चलन शोधा...' },
};
