// Telugu
export default {
  common: { save: 'సేవ్', cancel: 'రద్దు', delete: 'తొలగించు', edit: 'సవరించు', done: 'పూర్తయింది', back: 'వెనుకకు', next: 'తదుపరి', ok: 'సరే', yes: 'అవును', no: 'కాదు', loading: 'లోడ్ అవుతోంది...', error: 'లోపం', success: 'విజయం', retry: 'మళ్ళీ ప్రయత్నించు', search: 'వెతుకు', add: 'జోడించు', remove: 'తొలగించు', share: 'షేర్', settings: 'సెట్టింగ్స్', today: 'ఈరోజు', yesterday: 'నిన్న', thisWeek: 'ఈ వారం', earlier: 'ముందు' },
  tabs: { home: 'హోమ్', personal: 'వ్యక్తిగత', groups: 'గ్రూప్‌లు', insights: 'ఇన్‌సైట్స్', profile: 'ప్రొఫైల్' },
  home: { greeting: '{{timeOfDay}}, {{name}}', morning: 'శుభోదయం', afternoon: 'నమస్కారం', evening: 'శుభ సాయంత్రం', todaySpend: 'ఈరోజు ఖర్చు', monthSpend: 'ఈ నెల', quickAdd: 'త్వరగా జోడించు', reviewExpenses: 'ఖర్చులు చూడు', noTransactions: 'ఇంకా లావాదేవీలు లేవు', startTracking: 'మీ ఖర్చులను ట్రాక్ చేయడం ప్రారంభించండి' },
  groups: { title: 'గ్రూప్‌లు', newGroup: 'కొత్త గ్రూప్', noGroups: 'ఇంకా గ్రూప్‌లు లేవు', createFirst: 'స్నేహితులతో ఖర్చులు పంచుకోడానికి గ్రూప్ సృష్టించండి', allSettled: 'అంతా సెటిల్ అయింది', youOwe: 'మీరు {{amount}} ఇవ్వాలి', youAreOwed: 'మీకు {{amount}} రావాలి', settleUp: 'సెటిల్ చేయి', addExpense: 'ఖర్చు జోడించు', expenses: '{{count}} ఖర్చులు', trackGroup: 'ఈ గ్రూప్‌ను ట్రాక్ చేయి', trackGroupSub: 'చెల్లింపులను ఆటోమేటిక్‌గా గుర్తించి సమానంగా పంచు' },
  split: { amount: 'మొత్తం', description: 'వివరణ', descriptionPlaceholder: 'ఉదా: BBQ Nation లో డిన్నర్...', addNote: 'నోట్ జోడించు', notePlaceholder: 'సందర్భం కోసం నోట్ జోడించు...', category: 'వర్గం', splitType: 'పంపకం రకం', equal: 'సమానం', byAmount: 'మొత్తం ద్వారా', whosIn: 'ఎవరెవరు?', selectedOf: '{{total}} లో {{selected}} ఎంచుకోబడ్డారు', each: 'ఒక్కొక్కరికి {{amount}}', confirmSplit: 'స్ప్లిట్ నిర్ధారించు', splitWays: '{{count}} మందిలో పంచు', addGuest: 'అతిథి జోడించు', guestHint: 'ఒకసారి, సభ్యునికి ట్యాగ్ చేయబడింది', noteOptional: 'నోట్ (ఐచ్ఛికం)' },
  settle: { selectBalance: 'సెటిల్ చేయడానికి బ్యాలెన్స్ ఎంచుకోండి', settlePayment: 'చెల్లింపు సెటిల్', payTo: '{{name}} కు చెల్లింపు', totalDebt: 'మొత్తం బాకీ', settleAmount: 'సెటిల్ మొత్తం', fullSettlement: 'పూర్తి సెటిల్‌మెంట్', partial: 'పాక్షిక · మిగిలింది: {{amount}}', payUPI: 'UPI / కార్డ్ ద్వారా', opensPaymentApp: 'మీ పేమెంట్ యాప్ తెరవబడుతుంది', settledByCash: 'క్యాష్‌లో సెటిల్', markAsPaid: 'క్యాష్‌లో చెల్లించినట్లు గుర్తించు', wasPaymentDone: 'చెల్లింపు జరిగిందా?', yesPaymentDone: 'అవును, చెల్లింపు జరిగింది', markAsSettled: 'సెటిల్ అయినట్లు గుర్తించు', noPaymentFailed: 'కాదు, చెల్లింపు జరగలేదు', dontMark: 'సెటిల్ అయినట్లు గుర్తించకు' },
  profile: { title: 'ప్రొఫైల్', editName: 'మార్చడానికి టాప్ చేయండి', verified: 'ధృవీకరించబడింది', subscription: 'సబ్‌స్క్రిప్షన్', referEarn: 'రిఫర్ & సంపాదించు', emailDetection: 'ఈమెయిల్ లావాదేవీ గుర్తింపు', emailPrivacy: 'మీరు అనుమతిస్తే మాత్రమే మీ ఈమెయిల్‌ను కనెక్ట్ చేస్తాము.', connect: 'కనెక్ట్', disconnect: 'డిస్‌కనెక్ట్', notConnected: 'కనెక్ట్ కాలేదు', privacy: 'గోప్యత & డేటా', dataSafe: 'మీ డేటా భద్రంగా ఉంది', privacyDesc: 'Trackk ఈవెంట్-డ్రివెన్ SMS గుర్తింపును ఉపయోగిస్తుంది.', about: 'గురించి', appVersion: 'యాప్ వెర్షన్', signOut: 'సైన్ అవుట్', signOutConfirm: 'మీరు సైన్ అవుట్ చేయాలనుకుంటున్నారా?', language: 'భాష', currency: 'కరెన్సీ' },
  insights: { title: 'ఇన్‌సైట్స్', thisMonth: 'ఈ నెల', allTime: 'మొత్తం', topCategories: 'టాప్ వర్గాలు', recurring: 'పునరావృత చెల్లింపులు', trends: 'ఖర్చు ట్రెండ్స్' },
  goals: { title: 'పొదుపు లక్ష్యాలు', newGoal: 'కొత్త లక్ష్యం', dailyBudget: 'రోజువారీ బడ్జెట్', streak: 'స్ట్రీక్', saved: 'పొదుపు', target: 'లక్ష్యం' },
  trackers: { subscriptions: 'సబ్‌స్క్రిప్షన్‌లు', investments: 'పెట్టుబడులు', emis: 'EMI & రుణాలు', sync: 'సింక్', monthly: 'నెలవారీ', yearly: 'సంవత్సరవారీ', active: 'సక్రియం', noItems: 'ఏమీ కనుగొనబడలేదు', scanTip: 'మీ SMS మరియు ఈమెయిల్ నుండి {{type}} వెతుకుతాము' },
  reminders: { title: 'సెటిల్‌మెంట్ రిమైండర్', gentle1: '{{name}} లో {{amount}} పెండింగ్‌లో ఉంది', gentle2: 'రిమైండర్: {{name}} లో {{amount}} బాకీ. హడావిడి లేదు!', gentle3: '{{name}} లో {{amount}} సెటిల్ కాలేదు', gentle4: 'ఫ్రెండ్లీ రిమైండర్: {{name}} లో {{amount}} పెండింగ్' },
  currency: { title: 'కరెన్సీ', searchPlaceholder: 'కరెన్సీలు వెతకండి...' },
};
